from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import OrderViewSet

router = DefaultRouter()

# FIX: The prefix for your endpoint should be 'orders'.
# This registers the ViewSet at the 'orders/' path within this app's URL configuration.
router.register(r'orders', OrderViewSet, basename='order')

urlpatterns = [
    # This includes all the URLs generated by the router.
    # e.g., /orders/, /orders/{uuid}/, /orders/sync_shopify_orders/
    path('', include(router.urls)),
]
