# Generated by Django 5.0.2 on 2025-07-17 09:28

import companies.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDeleteOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('admin_user_id', models.UUIDField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_delete_otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Registration Number')),
                ('industry', models.CharField(choices=[('IT', 'Information Technology'), ('FINANCE', 'Finance'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('RETAIL', 'Retail'), ('MANUFACTURING', 'Manufacturing'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Industry')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopify_domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Shopify Domain')),
                ('shopify_access_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Shopify Access Token')),
                ('shiprocket_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Shiprocket Email')),
                ('shiprocket_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Shiprocket Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_customer_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Shopify Customer ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[companies.models.validate_phone_number], verbose_name='Phone')),
                ('number_of_orders', models.IntegerField(default=0, validators=[companies.models.validate_order_amount], verbose_name='Number of Orders')),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[companies.models.validate_amount], verbose_name='Total Amount Spent')),
                ('currency_code', models.CharField(blank=True, max_length=3, null=True, validators=[companies.models.validate_currency_code], verbose_name='Currency Code')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated At')),
                ('verified_email', models.BooleanField(default=False, verbose_name='Verified Email')),
                ('valid_email_address', models.BooleanField(default=False, verbose_name='Valid Email Address')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('tags', models.TextField(blank=True, null=True, validators=[companies.models.validate_tags], verbose_name='Tags')),
                ('lifetime_duration', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[companies.models.validate_amount], verbose_name='Lifetime Duration')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Can Delete')),
                ('default_address_formatted_area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Default Address Area')),
                ('default_address_line', models.CharField(blank=True, max_length=255, null=True, verbose_name='Default Address Line')),
                ('addresses', models.JSONField(blank=True, help_text='List of formatted address strings', null=True, verbose_name='All Addresses')),
                ('src', models.CharField(blank=True, max_length=500, null=True, verbose_name='Image Src')),
                ('cust_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer Code')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='companies.company')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDeleteOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_user_id', models.UUIDField()),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_delete_otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='department name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='companies.company')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
